terraform {
  required_version = ">= 1.9.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {
    resource_group {
      prevent_deletion_if_contains_resources = true
    }
    key_vault {
      purge_soft_delete_on_destroy    = false
      recover_soft_deleted_key_vaults = true
    }
  }
  subscription_id = "fa62ce43-1973-4cfa-8701-52edafaeb3ac"
  tenant_id       = "f6d676f9-f942-4aa8-9e4e-ab463391f2d9"
  use_oidc        = true
}

# ── Data sources ──────────────────────────────────────────────────────────────
# Read the current caller identity — who is running Terraform right now
# Used in Key Vault access policy so Terraform can manage secrets
data "azurerm_client_config" "current" {}

# ── Resource group ─────────────────────────────────────────────────────────────
resource "azurerm_resource_group" "module08_rg" {
  name     = "rg-adal-08-lab"
  location = "westus2"

  tags = {
    project     = "azure-dba-automation-lab"
    module      = "08"
    environment = "lab"
    managed_by  = "terraform"
    owner       = "srikanth.manchana"
  }
}

# ── Random suffix for Key Vault name ──────────────────────────────────────────
# Key Vault names must be globally unique across all of Azure
resource "random_string" "key_vault_suffix" {
  length  = 6
  special = false
  upper   = false
  numeric = true
  lower   = true
}

# ── Key Vault ──────────────────────────────────────────────────────────────────
resource "azurerm_key_vault" "sql_secrets" {
  name                = "kv-adal-08-${random_string.key_vault_suffix.result}"
  location            = azurerm_resource_group.module08_rg.location
  resource_group_name = azurerm_resource_group.module08_rg.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "standard"

  # Security settings
  enabled_for_disk_encryption     = false
  enabled_for_deployment          = false
  enabled_for_template_deployment = false
  rbac_authorization_enabled      = false
  purge_protection_enabled        = false
  soft_delete_retention_days      = 7
  public_network_access_enabled   = true

  # Access policy for Terraform — allows it to manage secrets
  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    secret_permissions = [
      "Get",
      "List",
      "Set",
      "Delete",
      "Purge",
      "Recover"
    ]
  }

  tags = azurerm_resource_group.module08_rg.tags
}

# ── Random password for SQL admin ─────────────────────────────────────────────
# Generated by Terraform — never typed by a human, never stored in code
resource "random_password" "sql_admin_password" {
  length           = 16
  special          = true
  min_upper        = 2
  min_lower        = 2
  min_numeric      = 2
  min_special      = 2
  override_special = "!@#$"
}

# ── SQL admin password stored in Key Vault ────────────────────────────────────
resource "azurerm_key_vault_secret" "sql_admin_password" {
  name         = "sql-admin-password"
  value        = random_password.sql_admin_password.result
  key_vault_id = azurerm_key_vault.sql_secrets.id

  content_type = "text/plain"

  tags = azurerm_resource_group.module08_rg.tags
}

# ── Outputs ───────────────────────────────────────────────────────────────────
output "key_vault_name" {
  value       = azurerm_key_vault.sql_secrets.name
  description = "Key Vault name — reference this in other modules via data source"
}

output "key_vault_id" {
  value       = azurerm_key_vault.sql_secrets.id
  description = "Key Vault resource ID"
}

output "key_vault_uri" {
  value       = azurerm_key_vault.sql_secrets.vault_uri
  description = "Key Vault URI — used to access secrets"
}

output "sql_admin_secret_name" {
  value       = azurerm_key_vault_secret.sql_admin_password.name
  description = "Name of the SQL admin password secret in Key Vault"
  sensitive   = false
}

output "sql_admin_password" {
  value       = random_password.sql_admin_password.result
  description = "SQL admin password — sensitive, stored in Key Vault"
  sensitive   = true
}